defaults:
  - trainer/callbacks: default
  - encoder: null
  - data: null
  - data@data.train_data_module: null
  - hparam_search: null
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  sweep:
    dir: ${oc.env:SWEEP_DIR}

output_dir:
command: ???
encoder: ???
model:
  _target_: aligner.text_video_grounding.TextVideoGroundingLightningModule
  init_temperature: 0.015
  fit_temperature: false
data: ???
trainer:
  _target_: pytorch_lightning.Trainer
  benchmark: false
  deterministic: false
  accelerator: gpu
  devices: -1
  strategy: dp
  logger:  # Need to use a list, so it can be overridden by Hydra if adding more loggers.
    - _target_: pytorch_lightning.loggers.TensorBoardLogger
      save_dir: .
      name:
      version: ""
  log_every_n_steps: 2
  num_sanity_val_steps: 4  # To make sure there's more than max top_k (10, used by R@10), otherwise it fails.
  gradient_clip_val: null
checkpoint_path:
seed: 42
silent: false
post_processing:
  watershed_threshold: 1.0
  watershed_scoring: max
  smoothing_function: SMA
  smoothing_window_size: 1
wandb: 
  enabled: False
  project_name: ResidualCLIP_zero_shot_evaluation
  